start_latent: consistency
verbose: false
cfg_schedule:
  - 0
  - 7
  - 11
  - 19
guiders:
- name: features_map_l2
  g_scale:
  - 0.5
  - 0.5
  - 0.5
  - 0.5
  kwargs: {}
noise_rescaling_setup:
  type: range_other_on_cfg_norm
  init_setup:
  - 0.0
  - 1.0
edit_types:
- animal-2-animal
- face-in-the-wild
- person-in-the-wild
